language: python
services:
  - postgresql
python:
  - 3.6

env:
  # todo we should have a dependent build on ahmia-index instead of
  # redefining values and manually running ahmia-index scripts further below
  - ES_URL=http://localhost:9200/
  - ES_TOR_INDEX=latest-tor
  - ES_I2P_INDEX=latest-i2p

before_install:
  # Install specific ES version
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.4.0.deb
  - sudo dpkg -i --force-confnew elasticsearch-6.4.0.deb
  - sudo service elasticsearch restart

  # Setup index (same applies here ~ should be a dependent build instead)
  - sleep 5  # give some time to ES to start
  - curl -O https://raw.githubusercontent.com/ahmia/ahmia-index/master/mappings_tor.json
  - curl -O https://raw.githubusercontent.com/ahmia/ahmia-index/master/mappings_i2p.json
  - curl -XPUT -i "${ES_URL}tor" -H 'Content-Type: application/json' \
         -d "@./mappings_tor.json"
  - curl -XPUT -i "${ES_URL}i2p" -H 'Content-Type: application/json' \
         -d "@./mappings_i2p.json"
  - curl -XPOST -i "${ES_URL}_aliases" -H "Content-Type: application/json" \
         -d "{\"actions\" : [{\"add\": {\"index\": \"tor\", \"alias\": \"latest-tor\"}}]}"
  - curl -XPOST -i "${ES_URL}_aliases" -H "Content-Type: application/json" \
         -d "{\"actions\" : [{\"add\": {\"index\": \"i2p\", \"alias\": \"latest-i2p\"}}]}"

install:
  - pip install -r requirements/prod.txt

before_script:
  - psql -c 'create database ahmiasite;' -U postgres
  - cd ahmia
  - cp ahmia/settings/example.env ahmia/settings/.env
  - python manage.py collectstatic --noinput -c
  - python manage.py migrate

script:
  - python manage.py test
